version: "3.9"

services:
  app:
    build: .
    container_name: ecom-whatsapp-bot
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - .:/app


networks:
    default:
        external:
            name: cluster