version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.15.3
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API (opcional)
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped


networks:
    default:
        external:
            name: cluster
            