version: '3.8'
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: unless-stopped



networks:
    default:
        external:
            name: cluster